version: "3.8"


services:
php:
image: php:8.2-apache
container_name: loja_php
ports:
- "8080:80"
volumes:
- ./src:/var/www/html
depends_on:
- db


db:
image: mysql:8.0
container_name: loja_mysql
restart: always
environment:
MYSQL_ROOT_PASSWORD: root
MYSQL_DATABASE: loja
MYSQL_USER: janine
MYSQL_PASSWORD: 12345
ports:
- "3306:3306"
volumes:
- ./sql:/docker-entrypoint-initdb.d
- mysql_data:/var/lib/mysql


phpmyadmin:
image: phpmyadmin/phpmyadmin
container_name: loja_phpmyadmin
restart: always
ports:
- "8081:80"
environment:
PMA_HOST: db
MYSQL_ROOT_PASSWORD: root


volumes:
mysql_data: